### PR TITLE
New PKGBUILD with icons and desktop file

### PR DESCRIPTION
**Pull request by marioortizmanero**
Hi!

I've created a new PKGBUILD that also installs icons and the desktop file. It's based on popular appimage packages, like joplin-appimage and freecad-appimage.

It depends on https://github.com/Nault/Nault/pull/283, as the icons aren't exported correctly right now.

Give it a try and let me know.

### CODE REVIEW

**Comment by agilob** [comment]
Do you want to add yourself to maintainers/contributors in the source or AUR?

**Comment by marioortizmanero** [comment]
sure! give me a sec to add it to the PKGBUILD

Edit: done

**Review by agilob — APPROVED** [review]
LGTM, same thing we did while ago in tutanota

**Comment by agilob** [comment]
I'll update upstream AUR package next time there is update in nault, thanks mate!

**Pull request merged**
